[package]
name = "docln_fetch"
version = "0.1.0"
edition = "2024"

[dependencies]
scraper = "0.24"
serde_json = "1.0"
chrono = "0.4"
anyhow = "1.0"
zip = "6.0"
sha2 = "0.10"
bytes = "1.10"

[dependencies.reqwest]
version = "0.12"
features = ["json"]

[dependencies.tokio]
version = "1"
features = ["full"]

[dependencies.serde]
version = "1.0"
features = ["derive"]